name: Benchmarks

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1" # Every Monday at 05:00 UTC

jobs:
  run-benchmarks:
    name: Run Benchmark Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.10'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-bench-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-bench-

      - name: Download dependencies
        run: go mod download

      - name: Run benchmarks
        run: |
          go test -run=^$ -bench=. -benchmem -benchtime=2s ./benchmark | tee bench-results.txt

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: bench-results.txt
